CREATE TABLE IF NOT EXISTS `x37bf_mediacat_trash` (
  `trash_id` int(11) NOT NULL AUTO_INCREMENT,
  `media_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id` int(11) NOT NULL COMMENT 'Original id',
  `folder_path` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extension` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_trashed` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_deleted` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `width` int(11) NOT NULL DEFAULT '0',
  `height` int(11) NOT NULL DEFAULT '0',
  `size` int(11) NOT NULL DEFAULT '0',
  `alt` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `caption` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` tinyint(3) NOT NULL DEFAULT '1',
  PRIMARY KEY (`trash_id`),
  KEY `folder_path` (`folder_path`),
  KEY `file_name` (`file_name`),
  KEY `state` (`state`),
  KEY `media_type` (`media_type`),
  KEY `original_id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;